#include "ergodox_ez.h"
#include "debug.h"
#include "action_layer.h"
#include "version.h"
#include "danielo515.h"


enum custom_keycodes
{
  PLACEHOLDER = SAFE_RANGE, // can always be here
  EPRM,
  RGB_SLD,
  ALT_TAB,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT_ergodox(KC_ESCAPE, KC_1, KC_2, KC_3, KC_4, KC_5, LCTL(KC_X), KC_DELETE, KC_Q, KC_W, KC_E, KC_R, KC_T, LCTL(KC_V), KC_COLN, KC_A, LT(3, KC_S), LT(2, KC_D), LT(4, KC_F), KC_G, KC_PIPE, KC_Z, KC_X, KC_C, KC_V, KC_B, LCTL(KC_C), LSFT(KC_LALT), OSM(MOD_LCTL), OSM(MOD_LALT), KC_LEFT, KC_RIGHT, ALT_T(KC_INSERT), KC_LGUI, KC_HOME, OSM(MOD_LSFT), LT(2, KC_BSPACE), KC_PLUS, TO(1), KC_6, KC_7, KC_8, KC_9, LT(3, KC_0), KC_DQUO, KC_UNDS, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_MINUS, KC_H, ALT_T(KC_J), RCTL_T(KC_K), LT(6, KC_L), KC_SCOLON, GUI_T(KC_QUOTE), KC_TAB, KC_N, KC_M, KC_COMMA, KC_DOT, KC_SLASH, LT(4, KC_KP_ASTERISK), LT(4, KC_ENTER), KC_DOWN, KC_LBRACKET, KC_RBRACKET, OSL(2), KC_AUDIO_MUTE, KC_ESCAPE, KC_END, KC_COLN, LT(3, KC_BSPACE), LT(4, KC_SPACE)),

  [1] = LAYOUT_ergodox(
    TD(COPY_PASTE)   , KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
    KC_TAB           , KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
    LT(5, KC_DELETE) , KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
    KC_GRAVE         , KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, TD(COPY_PASTE),
    KC_TRANSPARENT   , KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, OSM(MOD_LSFT), KC_TRANSPARENT, KC_PLUS, TO(7), KC_TRANSPARENT , KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_UNDS, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, ALT_TAB, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_ENTER, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_PIPE, KC_COLN, KC_TRANSPARENT),

  [2] = LAYOUT_ergodox(KC_ESCAPE,KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,KC_TRANSPARENT,KC_TRANSPARENT,KC_EXLM,KC_AT,KC_LCBR,KC_RCBR,KC_PIPE,KC_CALCULATOR,KC_TRANSPARENT,KC_HASH,KC_DLR,KC_TRANSPARENT,KC_RPRN,KC_GRAVE,RCTL(RSFT(KC_P)),KC_PERC,KC_CIRC,KC_LBRACKET,KC_RBRACKET,KC_TILD,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,RGB_TOG,RGB_HUI,KC_TRANSPARENT,KC_TRANSPARENT,RGB_HUD,KC_DELETE,KC_A,KC_B,KC_C,KC_D,KC_E,KC_BSPACE,KC_ENTER,KC_F,KC_7,KC_8,KC_9,KC_PERC,KC_TRANSPARENT,KC_HASH,KC_4,KC_5,KC_6,KC_PLUS,KC_KP_ASTERISK,KC_TRANSPARENT,KC_AMPR,KC_1,KC_2,KC_3,KC_SLASH,KC_BSLASH,KC_0,KC_COMMA,KC_DOT,KC_EQUAL,KC_TRANSPARENT,RGB_MOD,RGB_SLD,RGB_VAI,RGB_VAD,KC_BSPACE,KC_SPACE),

  [3] = LAYOUT_ergodox(RESET,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_LCBR,KC_RCBR,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_AT,KC_TRANSPARENT,KC_EQUAL,KC_RABK,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_LBRACKET,KC_RBRACKET,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,LALT(LSFT(KC_UP)),KC_HASH,KC_LABK,KC_RABK,KC_KP_ASTERISK,KC_PERC,KC_DLR,KC_AMPR,KC_LPRN,KC_RPRN,KC_MINUS,KC_KP_PLUS,KC_PIPE,LALT(LSFT(KC_DOWN)),KC_EXLM,KC_TILD,KC_CIRC,KC_PLUS,KC_QUES,KC_BSLASH,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,RESET,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_SPACE),

  [4] = LAYOUT_ergodox(KC_TRANSPARENT,KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,KC_TRANSPARENT,KC_TRANSPARENT,LCTL(KC_Q),LCTL(KC_W),KC_TRANSPARENT,KC_TRANSPARENT,LGUI(KC_UP),LALT(LSFT(KC_UP)),LCTL(LSFT(KC_P)),LCTL(KC_A),LCTL(KC_S),LCTL(KC_D),KC_TRANSPARENT,RGUI(KC_R),LCTL(LSFT(KC_F)),LCTL(KC_Z),LCTL(KC_X),KC_PSCREEN,KC_TRANSPARENT,LGUI(KC_DOWN),LALT(LSFT(KC_DOWN)),KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,LALT(KC_F4),KC_F6,KC_F7,KC_F8,KC_F9,KC_F10,KC_F11,LALT(KC_UP),LSFT(KC_HOME),LSFT(KC_LEFT),KC_UP,LSFT(KC_RIGHT),LSFT(KC_END),KC_F13,KC_HOME,KC_LEFT,KC_DOWN,KC_RIGHT,KC_END,KC_F12,LALT(KC_DOWN),LSFT(KC_INSERT),LCTL(LSFT(KC_J)),LSFT(KC_UP),KC_PGUP,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,LSFT(KC_DOWN),KC_PGDOWN,LGUI(KC_LEFT),LGUI(KC_RIGHT),KC_TRANSPARENT,KC_SYSTEM_SLEEP,KC_TRANSPARENT,KC_TRANSPARENT,KC_BSPACE,KC_TRANSPARENT),

  [5] = LAYOUT_ergodox(KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_SYSTEM_SLEEP,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,LCTL(KC_TAB),LCTL(LSFT(KC_TAB)),LGUI(KC_D),LCTL(KC_F),KC_TRANSPARENT,LGUI(KC_L),KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_ASRP,KC_ASTG,KC_TRANSPARENT,KC_TRANSPARENT,LSFT(KC_F9),KC_TRANSPARENT,KC_TRANSPARENT,KC_ASUP,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,LCTL(LGUI(KC_LEFT)),LCTL(LGUI(KC_RIGHT)),KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_ASDN,LCTL(KC_T),KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT),

  [6] = LAYOUT_ergodox(KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_ACCEL2,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_WH_DOWN,KC_MS_UP,KC_MS_WH_UP,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_LEFT,KC_MS_DOWN,KC_MS_RIGHT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_BTN3,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_BTN1,KC_MS_BTN2,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_PGUP,LCTL(LGUI(KC_RIGHT)),KC_MS_WH_UP,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,LGUI(RCTL(KC_LEFT)),KC_MS_WH_DOWN,LCTL(KC_C),KC_TRANSPARENT,KC_MEDIA_STOP,KC_MEDIA_PLAY_PAUSE,KC_PGDOWN,LCTL(LSFT(KC_N)),LCTL(LSFT(KC_J)),KC_MEDIA_PREV_TRACK,KC_MEDIA_NEXT_TRACK,KC_TRANSPARENT,KC_TRANSPARENT,KC_AUDIO_VOL_UP,KC_AUDIO_VOL_DOWN,KC_AUDIO_MUTE,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT),

  [7] = LAYOUT_ergodox(KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_UP,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_LEFT       ,KC_DOWN,KC_RIGHT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT),

  [8] = LAYOUT_ergodox(KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_E,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_ENTER,KC_TRANSPARENT,KC_A,KC_S,KC_D,KC_F,KC_TRANSPARENT,KC_TRANSPARENT,KC_Z,KC_X,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_SPACE,KC_TRANSPARENT,KC_PGUP,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_PGDOWN,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_ENTER,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_SPACE),

};


qk_tap_dance_action_t tap_dance_actions[] = {
  [COPY_PASTE] = ACTION_TAP_DANCE_FN(td_copy_paste),
};

const uint16_t PROGMEM fn_actions[] = {
    [1] = ACTION_LAYER_TAP_TOGGLE(1)};

// leaving this in place for compatibilty with old keymaps cloned and re-compiled.
const macro_t *action_get_macro(keyrecord_t *record, uint8_t id, uint8_t opt)
{
  switch (id)
  {
  case 0:
    if (record->event.pressed)
    {
      SEND_STRING(QMK_KEYBOARD "/" QMK_KEYMAP " @ " QMK_VERSION);
    }
    break;
  }
  return MACRO_NONE;
};

bool altPressed = false;

bool process_record_user(uint16_t keycode, keyrecord_t *record)
{
  switch (keycode)
  {
    // dynamically generate these.
    case EPRM:
      if (record->event.pressed)
      {
        eeconfig_init();
      }
      return false;
      break;
    case RGB_SLD:
      if (record->event.pressed)
      {
        rgblight_mode(1);
      }
      return false;
      break;
      //First time alt + tab, and alt stays sticky. Next press we just send tab. Any other key releases the alt
    case ALT_TAB:
      if (record->event.pressed)
      {
        if (altPressed)
        {
          tap_code(KC_TAB);
        }
        else
        {
          altPressed = true;
          layer_on(7); // go to movement layer
          register_code(KC_LALT);
          tap_code(KC_TAB);
        }
      }
      return false;
    // avoid alt releasing if the key is of movement
    case KC_RIGHT ... KC_UP:
      if (altPressed)
      {
        return true; // yes QMK, do your stuff
      }
  }
  // Reset sticky alt tab
  if (altPressed)
  {
    unregister_code(KC_LALT);
    altPressed = false;
    layer_off(7);
    return false;
  }
  return true;
}

uint32_t layer_state_set_user(uint32_t state)
{

  uint8_t layer = biton32(state);

  ergodox_board_led_off();
  ergodox_right_led_1_off();
  ergodox_right_led_2_off();
  ergodox_right_led_3_off();
  switch (layer)
  {
  case 1:
    ergodox_right_led_1_on();
    rgblight_setrgb(0, 255, 0); // green
    break;
  case 2:
    ergodox_right_led_2_on();
    rgblight_setrgb(0, 0, 255);
    break;
  case 3:
    ergodox_right_led_3_on();
    rgblight_setrgb(255, 0, 0);
    break;
  case 4:
    ergodox_right_led_1_on();
    ergodox_right_led_2_on();
    rgblight_setrgb(200, 65, 0);
    break;
  case 5:
    ergodox_right_led_1_on();
    ergodox_right_led_3_on();
    rgblight_setrgb(0, 80, 33);
    break;
  case 6:
    ergodox_right_led_2_on();
    ergodox_right_led_3_on();
    rgblight_setrgb(0, 10, 200);
    break;
  case 7:
    ergodox_right_led_1_on();
    ergodox_right_led_2_on();
    ergodox_right_led_3_on();
    rgblight_setrgb(90, 150, 90);
    break;
  default:
    rgblight_setrgb(0x00, 0xFF, 0xFF);
    break;
  }
  return state;
};
